version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      API_URL: http://localhost:3000/
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
      INLINE_RUNTIME_CHUNK: 'false'
    ports:
      - '3000:3000'
    command: npm run server
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:latest
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
